TAGS = {
    101: {"label": "Goal", "description": "Goal"},
    102: {"label": "own_goal", "description": "Own goal"},
    301: {"label": "assist", "description": "Assist"},
    302: {"label": "keyPass", "description": "Key pass"},
    1901: {"label": "counter_attack", "description": "Counter attack"},
    401: {"label": "Left", "description": "Left foot"},
    402: {"label": "Right", "description": "Right foot"},
    403: {"label": "head/body", "description": "Head/body"},
    1101: {"label": "direct", "description": "Direct"},
    1102: {"label": "indirect", "description": "Indirect"},
    2001: {"label": "dangerous_ball_lost", "description": "Dangerous ball lost"},
    2101: {"label": "blocked", "description": "Blocked"},
    801: {"label": "high", "description": "High"},
    802: {"label": "low", "description": "Low"},
    1401: {"label": "interception", "description": "Interception"},
    1501: {"label": "clearance", "description": "Clearance"},
    201: {"label": "opportunity", "description": "Opportunity"},
    1301: {"label": "Feint", "description": "Feint"},
    1302: {"label": "missed ball", "description": "Missed ball"},
    501: {"label": "free_space_r", "description": "Free space right"},
    502: {"label": "free_space_l", "description": "Free space left"},
    503: {"label": "take_on_l", "description": "Take on left"},
    504: {"label": "take_on_r", "description": "Take on right"},
    1601: {"label": "sliding_tackle", "description": "Sliding tackle"},
    601: {"label": "anticipated", "description": "Anticipated"},
    602: {"label": "anticipation", "description": "Anticipation"},
    1701: {"label": "red_card", "description": "Red card"},
    1702: {"label": "yellow_card", "description": "Yellow card"},
    1703: {"label": "second_yellow_card", "description": "Second yellow card"},
    1201: {"label": "gb", "description": "Position: Goal low center"},
    1202: {"label": "gbr", "description": "Position: Goal low right"},
    1203: {"label": "gc", "description": "Position: Goal center"},
    1204: {"label": "gl", "description": "Position: Goal center left"},
    1205: {"label": "glb", "description": "Position: Goal low left"},
    1206: {"label": "gr", "description": "Position: Goal center right"},
    1207: {"label": "gt", "description": "Position: Goal high center"},
    1208: {"label": "gtl", "description": "Position: Goal high left"},
    1209: {"label": "gtr", "description": "Position: Goal high right"},
    1210: {"label": "obr", "description": "Position: Out low right"},
    1211: {"label": "ol", "description": "Position: Out center left"},
    1212: {"label": "olb", "description": "Position: Out low left"},
    1213: {"label": "or", "description": "Position: Out center right"},
    1214: {"label": "ot", "description": "Position: Out high center"},
    1215: {"label": "otl", "description": "Position: Out high left"},
    1216: {"label": "otr", "description": "Position: Out high right"},
    1217: {"label": "pbr", "description": "Position: Post low right"},
    1218: {"label": "pl", "description": "Position: Post center left"},
    1219: {"label": "plb", "description": "Position: Post low left"},
    1220: {"label": "pr", "description": "Position: Post center right"},
    1221: {"label": "pt", "description": "Position: Post high center"},
    1222: {"label": "ptl", "description": "Position: Post high left"},
    1223: {"label": "ptr", "description": "Position: Post high right"},
    901: {"label": "through", "description": "Through"},
    1001: {"label": "fairplay", "description": "Fairplay"},
    701: {"label": "lost", "description": "Lost"},
    702: {"label": "neutral", "description": "Neutral"},
    703: {"label": "won", "description": "Won"},
    1801: {"label": "accurate", "description": "Accurate"},
    1802: {"label": "not accurate", "description": "Not accurate"},
}

DEFAULT_ARROW_PARAMS = {
    "width": 2,
    "headwidth": 2,
    "headlength": 2,
    "headaxislength": 2,
    "alpha": 1,
}

COLOR_MAP = {"Pass": "blue", "Shot": "red", "Free Kick": "blue", "Corner Kick": "blue"}
